# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kyleopen/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES += \
    vendor/samsung/kyleopen/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/samsung/kyleopen/proprietary/lib/libnv.so:obj/lib/libnv.so

PRODUCT_COPY_FILES += \
    vendor/samsung/kyleopen/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/kyleopen/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/kyleopen/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/kyleopen/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/kyleopen/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/kyleopen/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/kyleopen/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/kyleopen/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/kyleopen/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/samsung/kyleopen/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/kyleopen/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/kyleopen/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/kyleopen/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
    vendor/samsung/kyleopen/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/kyleopen/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/kyleopen/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/kyleopen/proprietary/media/LMprec_508.emd:system/media/LMprec_508.emd \
    vendor/samsung/kyleopen/proprietary/media/PFFprec_600.emd:system/media/PFFprec_600.emd \
    vendor/samsung/kyleopen/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
    vendor/samsung/kyleopen/proprietary/lib/libDivxDrm[1].so:system/lib/libDivxDrm[1].so \
    vendor/samsung/kyleopen/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/samsung/kyleopen/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/samsung/kyleopen/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/samsung/kyleopen/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/samsung/kyleopen/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/kyleopen/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/kyleopen/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/kyleopen/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/kyleopen/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/kyleopen/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/kyleopen/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/kyleopen/proprietary/bin/netcfg:system/bin/netcfg \
    vendor/samsung/kyleopen/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/kyleopen/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/kyleopen/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/kyleopen/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/samsung/kyleopen/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/samsung/kyleopen/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/samsung/kyleopen/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/kyleopen/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/samsung/kyleopen/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/samsung/kyleopen/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/samsung/kyleopen/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/samsung/kyleopen/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/kyleopen/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/samsung/kyleopen/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/samsung/kyleopen/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/kyleopen/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/samsung/kyleopen/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/samsung/kyleopen/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/kyleopen/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/samsung/kyleopen/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/samsung/kyleopen/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/samsung/kyleopen/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/samsung/kyleopen/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/samsung/kyleopen/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/kyleopen/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/kyleopen/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/samsung/kyleopen/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/samsung/kyleopen/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/kyleopen/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/kyleopen/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/kyleopen/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/samsung/kyleopen/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/samsung/kyleopen/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so \
    vendor/samsung/kyleopen/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/kyleopen/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/samsung/kyleopen/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
    vendor/samsung/kyleopen/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/samsung/kyleopen/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-3.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-3.bin \
    vendor/samsung/kyleopen/proprietary/lib/modules/ath6kl_sdio.ko:system/lib/modules/ath6kl_sdio.ko \
    vendor/samsung/kyleopen/proprietary/lib/modules/cfg80211.ko:system/lib/modules/cfg80211.ko
